### ISSUE TITLE
Sui Testnet coins airdrop bug

### ISSUE THREAD

**Issue by timoha2012** [suiet/suiet#105]
![image](https://user-images.githubusercontent.com/116392629/197293087-c6d94d60-5a7f-41e7-b51b-14639c20f46d.png)

Hello! 
Why is it even possible to claim an airdrop of Testnet Sui coins?
No info about opening testnet was from the Sui team.

Is it internal testing from Suiet development team or what?

**Comment by bruceeewong** [comment]
Well the testnet is alive but the official Sui team didn't say it. It works actually.
