### ISSUE TITLE
I can't send SUI token from Sui wallet to Suiet wallet. I use the testnet network. I'm a developer, how can i help you?

### ISSUE THREAD

**Issue by nguyennamit1998** [suiet/suiet#107]
I can't send the SUI token from Sui wallet to Suiet wallet. I use testnet network. I'm a developer, how can I help you?

**Comment by bruceeewong** [comment]
I recommend you to use devnet for now, cuz testnet has not been officially announced

**Comment by nguyennamit1998** [comment]
ok

Vào Th 7, 22 thg 10, 2022 vào lúc 11:54 brrruski ***@***.***>
đã viết:
