### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Gridim07** [suiet/suiet#109]
Why the history always showing empty even though i made transactions in this account ?

**Comment by fredliang44** [comment]
Hi @Gridim07 , Mysten(Sui) just changed Sui API, but SDK hasn't made the adjustment. We expect at the end of next week we can publish the fix to online users. Thanks for your patience

**Comment by Gridim07** [comment]
> Hi @Gridim07 , Mysten(Sui) just changed Sui API, but SDK hasn't made the adjustment. We expect at the end of next week we can publish the fix to online users. Thanks for your patience

Thanks for the answer.
