### ISSUE TITLE
Error when minting NFT

### ISSUE THREAD

**Issue by DuanVu** [suiet/suiet#116]
Hi guys,

I met this error when minting NFT in devnet.
`Mint NFT failed: Error executing transaction with request type: Error: RPC Error: Internal error - Error checking transaction input objects: [IncorrectSigner { error: "Object 0x4bd344daee981502263876dc448963c1a423825e is owned by account address 0x8cc5c966798d26222774039d03c5948a327fedc0, but signer address is 0x143d91c90b28612fd27744fdd808c230b3f8a3cd" `

My wallet address: 0x143d91c90b28612fd27744fdd808c230b3f8a3cd
It seems be conflicted between my wallets.

**Comment by Akpen05** [comment]
hi guys
in cant get a Domain name it keeps saying error
my address 0xada389ae2ae59beaa1c1db256e072731fe5d14a5::suiname_nft::NamesGroup
0xa2ae...13aa

**Comment by bruceeewong** [comment]
@DuanVu This bug has been fixed, feel free to use Suiet.
