### ISSUE TITLE
Error on Airdrop button

### ISSUE THREAD

**Issue by Blackmaul** [suiet/suiet#117]
unexpecteded token '<', "<!DOCTYPE "... is not valid JSON  after i click the airdrop button

**Comment by pavanpalakurthi** [comment]
unexpecteded token '<', "<!DOCTYPE "... is not valid JSON after i click the airdrop button

I'm getting this type of error

**Comment by goddes03** [comment]
пишет "Coin Transfer Failed `Failed to transfer any coins to the requestor`"
когда нажимаю на кнопку Airdrop
