### ISSUE TITLE
wallet not receiveng SUI on devnet

### ISSUE THREAD

**Issue by cryptonite75** [suiet/suiet#118]
after applying on discord devnet-faucet to get SUI, I got the following message: 
"5 test Sui objects are heading to your wallet, check https://explorer.devnet.sui.io/addresses/0x162c5e756bb42d0afac59c770f65d1a3b2d71ac3 or with wallet cli sui client gas!"
cannot proceed or solve. any help?

**Comment by bruceeewong** [comment]
Hi, you can get faucet on the wallet now. Feel free to play with it.
