### ISSUE TITLE
The connection SUI wallet

### ISSUE THREAD

**Issue by siveing** [suiet/suiet#122]
Even if rejected it still return connected to true, so please check and complete it. it might be better in next versions. 

Thanks

**Comment by bruceeewong** [comment]
Can you please provide more details about it? Such as reproduce steps, screenshots etc?

**Comment by bruceeewong** [comment]
I wonder if you are using the old version of Sui react adapter? 
There is a issue of Sui react adapter which might be related: https://github.com/MystenLabs/sui/issues/5052

**Comment by siveing** [comment]
> 

Ahhh I see, let me try. Thanks you

**Comment by siveing** [comment]
Anyway, I have visited the link attached but I cannot even view it (Page not found). Could you help to check?

**Comment by fredliang44** [comment]
The link is available from my side, the root cause is Sui wallet is using the "fake" disconnect. You can try out our Suiet wallet to check out whether the problem has gone
