### ISSUE TITLE
error in mining nft 

### ISSUE THREAD

**Issue by armtt** [suiet/suiet#123]
I got two wallet account， when i switch from one to another and mint，the errors will show：

Mint NFT failed: Error executing transaction with request type: Error: RPC Error: Internal error - Error checking transaction input objects: [IncorrectSigner { error: "Object 0x6e9de1db4b82e03d40267ca1fc547f75ab2a1011 is owned by account address 0xd3ef15d875922186f04edd187aaf53cc59d3c400, but signer address is 0x072f7eab9104020a44b9180344f7433e12dee30e" }]} (code: -5000)

**Comment by bruceeewong** [comment]
This bug has been detected and solved, please update wallet extension version to v0.1.19. Hope you enjoy Suiet!
