### ISSUE TITLE
Can't recieve airdrop by sui wallet 

### ISSUE THREAD

**Issue by duongbui2708** [suiet/suiet#125]
Dear team,

I installed Sui Wallet extendtion on my chrome, but when I clicked on airdrop button it notify "you have been rate limited, please retry again 6 hours lastter". althought, the last time i received it was 2 day ago.

Can you fix it!!!

thank you.

**Comment by krscmax** [comment]
same issue

**Comment by fredliang44** [comment]
@duongbui2708 hi, sorry for inconvenience. The rate limits logic is controlled by Mystem(sui) team, we are not able to make any adjustments. You can try switching to different network to check whether the issue has gone.
