### ISSUE TITLE
discord invalid link on doc

### ISSUE THREAD

**Issue by Utep47** [suiet/suiet#126]
invalid discord address, 
![image](https://user-images.githubusercontent.com/117263928/199438216-74a0524e-00d5-4c7a-80ad-6881ebcc9bf0.png)

**Comment by fredliang44** [comment]
Hi,where have you got the link?(url or screenshot)

**Comment by Utep47** [comment]
https://suiet.app/docs/how-to-get-sui-tokens
[image: 0a45149e-88a2-42bc-b78f-52804dadb455.png]
https://discord.gg/pZEGqXENeH thats link is invalid
[image: image.png]

Pada tanggal Jum, 4 Nov 2022 pukul 14.48 Fred Liang <
***@***.***> menulis:

**Comment by bruceeewong** [comment]
@Utep47 Hi, we have updated the discord link on the website, feel free to check it out
