### ISSUE TITLE
[Feature] Support for other transaction kind's (`pay`, `bytes`, ...) in `signAndExecuteTransaction`

### ISSUE THREAD

**Issue by admin-aftermath** [suiet/suiet#134]
I see that you guys have a [TODO for adding new transaction types](https://github.com/suiet/suiet/blob/main/packages/chrome/src/scripts/background/bg-api/dapp.ts#L313), but I was wondering if you have road mapped adding support for `pay` transactions?

**Comment by bruceeewong** [comment]
Sure, we haven't support pay yet, but we would support it in the next week

**Comment by admin-aftermath** [comment]
I am generalizing this issue instead of opening up a new issue per transaction type

**Comment by bruceeewong** [comment]
@admin-aftermath Hi, we've solved this issue. Please update your wallet to v0.1.32.
