### ISSUE TITLE
test token support

### ISSUE THREAD

**Issue by Itztarunk51** [suiet/suiet#135]
initially test tokens are valid,But  now the test tokens are not not supporting for validating nfts,dapps etc
sui wallet address:0x72b1c58fde74450b5f7805152b4c5e61192046d8

**Comment by bruceeewong** [comment]
Sorry could you be more specific for your case? What do you mean by "validating nfts,dapps"?

**Comment by Russiansf** [comment]
Hello. I can't get test tokens. Returns an error.
![1111111111111111](https://user-images.githubusercontent.com/116181758/210455162-4f095027-83a0-4fea-9b2e-637e9547228c.png)
