### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by gabrielnuniez** [suiet/suiet#140]
help me? my wallet does not recognize my seed phrase, it tells me that it is empty, help
![Captura de pantalla (4)](https://user-images.githubusercontent.com/122934475/213007716-f20ef310-5e03-4ee7-8cfb-f273a3609398.png)

**Comment by fredliang44** [comment]
@gabrielnuniez Thanks for reporting, we have published a new version with the bugfix of this issue. You can follow this guide to upgrade to the latest version `v0.1.40`. https://suiet.app/docs/how-to-upgrade-extension
