### ISSUE TITLE
Could you update the sdk about offical sui wallet?

### ISSUE THREAD

**Issue by Gary20001016** [suiet/suiet#145]
https://github.com/MystenLabs/sui/pull/8690
it is about the signMessage function
thanks

**Comment by fredliang44** [comment]
> https://github.com/MystenLabs/sui/pull/8690
> 
> it is about the signMessage function
> 
> thanks

https://kit.suiet.app/docs/CanIUse Suiet already supported sign message. You can check this doc for api capabilities.
