### ISSUE TITLE
the wallet is stuck

### ISSUE THREAD

**Issue by vien229** [suiet/suiet#151]
sui wallet is stuck and need a refresh , but the respon is same

**Comment by Aditfsyah1** [comment]
sui wallet stuck, please make some fixing for the good future Crypto. Thanks

**Comment by bruceeewong** [comment]
Could u please provide more information such as errors or screenshots?

**Comment by fredliang44** [comment]
Hi, that was cause by a performance issue from Sui fullnodes, you can try again now.
