### ISSUE TITLE
Tokens not visible when sending to another adress

### ISSUE THREAD

**Issue by biggs-RMRK** [suiet/suiet#152]
When I want to send SUI tokens to another adress it's impossible to select any tokens to send because it's simply not displayed 
<img width="358" alt="Capture d’écran 2023-03-31 à 09 20 04" src="https://user-images.githubusercontent.com/128833751/229051248-a7728e90-c30f-4489-bceb-e344e214204b.png">

**Comment by bruceeewong** [comment]
Hi, this issue may be caused by testnet's instability. Would you try again and give feedbacks?

**Comment by fredliang44** [comment]
Hi, that was caused by a performance issue from Sui fullnodes, you can try again now.

Please feel free to reopen if you still experiencing the issue.
