### ISSUE TITLE
wallet connection problem

### ISSUE THREAD

**Issue by 06Kazim** [suiet/suiet#154]
When trying to connect to wallet from swap, it says chrome connection required even though Chrome is attached

![Screenshot_20230331-230557_Kiwi Browser](https://user-images.githubusercontent.com/118134093/229219646-d7498ca0-c980-46e4-898d-d2065b37a21f.jpg)

**Comment by Badlaan** [comment]
Hard to connect

**Comment by cillionaireclub** [comment]
> When trying to connect to wallet from swap, it says chrome connection required even though Chrome is attached
> 
> ![Screenshot_20230331-230557_Kiwi Browser](https://user-images.githubusercontent.com/118134093/229219646-d7498ca0-c980-46e4-898d-d2065b37a21f.jpg)

same problem with me

**Comment by 2efPer** [comment]
Same problem

**Comment by NebylicaNikita** [comment]
has anyone found a solution to the problem?

**Comment by 06Kazim** [comment]
Wallet connnection problem yes chorem

**Comment by bruceeewong** [comment]
Hi there, if you are using the v0.2.x version of Suiet Wallet, then it should be the problem of dapp's outdated wallet kit. As the testnet just was launched, please give the dapp teams some time to update their websites.

**Comment by laci141** [comment]
Suiet Wallet, then it should be the problem of dapp's outdated wallet kit. As the testnet just was launched, please give the dapp teams some time to update their websites.no connect ethos wallet ...sui wallet,,,suit wallet

**Comment by fredliang44** [comment]
Hi, that was cause by a Sui network upgrade, the apps on Sui should have upgraded their kit. You can try again now!
