### ISSUE TITLE
Balance Update

### ISSUE THREAD

**Issue by Writelijah** [suiet/suiet#156]
After an initial deposit of funds into the wallet, the balance of account doesn't change automatically it needs to be refreshed and this does not work for cases where speedy transaction is required

**Comment by bruceeewong** [comment]
Hi, what type of device are you using, PC or mobile? As the transaction result need to be fetched from testnet, the speed is not promised, but also shouldn't be too long. 
We've added polling fetching logic for all the assets, please feel free to upgrade to wallet with version >=0.2.1 and give feedbacks, thank you!

**Comment by fredliang44** [comment]
Closed for being long time with no response, please feel free to reopen it if you're still experiencing this.
