### ISSUE TITLE
The problem of connection with wallets,

### ISSUE THREAD

**Issue by aazami759** [suiet/suiet#159]
Hello and respect to the wallet, it does not connect well, the connection between the web and the wallet is not very strong.

**Comment by bruceeewong** [comment]
Hi there, if you are using the v0.2.x version of Suiet Wallet, then it should be the problem of dapp's outdated wallet kit. As the testnet just was launched, please give the dapp teams some time to update their websites.

**Comment by Adrianoaff** [comment]
Não consigo conectar minha carteira sui com outras carteiras. estou usando o navegador kiwi

**Comment by Adrianoaff** [comment]
Alguém pode mi ajudar eu não tenho computador 😔😔 o

**Comment by bruceeewong** [comment]
@Adrianoaff We haven't done some optimization for mobile browsers like kiwi now. We might deal with it in the future.

**Comment by fredliang44** [comment]
Closed for being long time with no response, please feel free to reopen it if you're still experiencing this.
