### ISSUE TITLE
i can't connect suiet or sui wallet to Dapp's websites.

### ISSUE THREAD

**Issue by VCBOSE2025** [suiet/suiet#160]
I can't connect SUIET or SUI wallet to Dapp's websites. it was saying to install the extension again even though I installed it in my chrome browser.

Example: 

https://movex.exchange/
https://suiswap.app/
https://app.turbos.finance/trade/perpetual
and etc.

**Comment by gaborveszpremi** [comment]
Same here, Suiet installed and open, Sui Wallet installed and open, but https://suiswap.suimo.xyz/ sends message: "You haven’t install this wallet" for both.  (Chrome / Brave browser)

**Comment by Pkcnick** [comment]
Same hete

**Comment by Pkcnick** [comment]
Same here

**Comment by rizukinae** [comment]
Me too, please somebody here tell me how to fix this. So frustrated 😢

**Comment by bruceeewong** [comment]
Hi there, if you are using the v0.2.x version of Suiet Wallet, then it should be the problem of dapp's outdated wallet kit. As the testnet just was launched, please give the dapp teams some time to update their websites.

**Comment by ragib70** [comment]
Thank God, I came to this thread, I have been banging my head from last 5 days connecting sui wallet to the dapps, but it says not installed though I have it installed.

**Comment by Jfrance99** [comment]
me too lol

**Comment by Manifestbassey** [comment]
AM TRIED

**Comment by imraz423** [comment]
same here i minted nft with suiet wallet and trying to stake on mobius but the dapp only detects my sui wallet and not the suiet

**Comment by fredliang44** [comment]
Hi, that was caused by a Sui network upgrade, the apps on Sui should have upgraded their kit. You can try again now.

If you still experience this issue, please contact the website admin.

**Comment by Heraldixh** [comment]
Hi, thank you for your support. It Is also not connecting SNS.domains
