### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by ryttesh** [suiet/suiet#161]
All types of dapp not working properly..

**Comment by bruceeewong** [comment]
Hi there, if you are using the v0.2.x version of Suiet Wallet, then it should be the problem of dapp's outdated wallet kit. As the testnet just was launched, please give the dapp teams some time to update their websites.

**Comment by Bossquida** [comment]
Cannot connect wallet into suidex

**Comment by roster90** [comment]
same issue, i can't connect to sui wallet with suiet/wallet-kit version 0.1.26.

**Comment by fredliang44** [comment]
Hi, that was cause by a Sui network upgrade, the apps on Sui should have upgraded their kit. You can try again now
