### ISSUE TITLE
Connection issues with wallet

### ISSUE THREAD

**Issue by neelaylko** [suiet/suiet#163]
pfa

**Comment by danat0** [comment]
i have this problem too

**Comment by steve11-jj** [comment]
me too

**Comment by imayyanksingh** [comment]
Already installed wallet, but Dapps not compatible and reintallion is asked again n again.

**Comment by fredliang44** [comment]
Hi, that was cause by a Sui network upgrade, the apps on Sui should have upgraded their kit. You can try again now
