### ISSUE TITLE
Can not display account if the accout has a lot txs

### ISSUE THREAD

**Issue by AurevoirXavier** [suiet/suiet#177]
<img width="310" alt="image" src="https://user-images.githubusercontent.com/16152305/230907020-e007b2d1-219e-43a9-931d-e7cdac82fed2.png">

Around 50k txs.

Infinity loading.

**Comment by bruceeewong** [comment]
Sure, we will look into this

**Comment by AurevoirXavier** [comment]
Actually, there are two questions.

If the tx amount is too big, the history component will get stuck.
If the object amount is too big, the balance component will get stuck.

I merged 100k coins. The balance component works now.

**Comment by bruceeewong** [comment]
Thanks for the information! Working hard on that!

**Comment by bruceeewong** [comment]
Please update to version v0.2.7. The issue here should be fixed.
