### ISSUE TITLE
Local environnement, impossible to build app

### ISSUE THREAD

**Issue by quentingosset** [suiet/suiet#178]
I would like to help you by proposing a PR if I can achieve the following outcome: https://github.com/suiet/suiet/issues/172
However, by following all your build steps I am unable to open the application. and I get the following errors: 

![image](https://user-images.githubusercontent.com/6824137/230972364-530cbcbd-4d6e-4bba-9600-d1871d01caee.png)
![image](https://user-images.githubusercontent.com/6824137/230972672-d058e1ff-938e-41fe-ab31-8c5ba442f70e.png)

Do you use a specific version of nodejs ?

**Comment by bruceeewong** [comment]
Nope, we are using Chrome storage API so the extension can only work in extension mode. What you need to do is to load the `dist` folder into your Chrome Extension panel
