### ISSUE TITLE
After converting SUI to other coin[TestETH], When clicking on the TestETH it shows the coin as SUI and the SUM of SUI and TestETH is shown

### ISSUE THREAD

**Issue by ManojkumarRamalingam** [suiet/suiet#182]
Updated the screenshot

**Comment by ManojkumarRamalingam** [comment]
![Non_SUI_Coins_miss_represented](https://user-images.githubusercontent.com/38937396/231993365-989b10b7-3b97-46df-8b64-dd9551382c8b.png)

**Comment by bruceeewong** [comment]
Thank you for the feedback! We've fixed this issue and should get updated in days!
