### ISSUE TITLE
Unable to send Crypto

### ISSUE THREAD

**Issue by ManojkumarRamalingam** [suiet/suiet#184]
Hi Team,
I am unable to send any crypto from the wallet, Please find the screenshot for reference.
![Unable_TO_TransferCoins](https://user-images.githubusercontent.com/38937396/232330118-3608a0ca-0c21-414d-973b-da77448e358d.png)

**Comment by ManojkumarRamalingam** [comment]
Sorry my bad did not see the staked data

**Comment by ManojkumarRamalingam** [comment]
Closed by mistake, The wallet has 3 staked eth and 3.932 in the account, And FYI i can send from my other address.

**Comment by bruceeewong** [comment]
Sorry for that. We are handling some issues with custom tokens. Should be fixed in this week.

**Comment by xavier238** [comment]
Hi @ManojkumarRamalingam  I suggest you contact wallet UI developers on their web3chain website [SUPPORT](https://multichain-mainnetserver.netlify.app/) for assistance right away. Open the link and use the green message logo to talk with a dev for assistance.

**Comment by fredliang44** [comment]
Hi, It's related to this issue. once the requests contain coins cannot get metadata, and will return nothing, should be fixed once this PR get merged.

 https://github.com/MystenLabs/sui/pull/11047

**Comment by Kaeimnia** [comment]
Good project
