### ISSUE TITLE
I have problem while importing my key

### ISSUE THREAD

**Issue by Iceeekh** [suiet/suiet#201]
I need a support help with this

**Comment by Iceeekh** [comment]
![Screenshot 2023-06-06 002708](https://github.com/suiet/suiet/assets/135648384/61f0e897-0a87-4505-9f3a-bb4b4b2c6ed6)
![photo_2023-06-06_00-35-15](https://github.com/suiet/suiet/assets/135648384/2bc9efc5-3cd8-4e93-aa61-0fba8a6e2474)

**Comment by Iceeekh** [comment]
![photo_2023-06-06_00-35-22](https://github.com/suiet/suiet/assets/135648384/adee68a5-c71e-4a90-874b-1486451cd8cc)

**Comment by Iceeekh** [comment]
I can't send this out....

**Comment by bruceeewong** [comment]
@Iceeekh Hi, have you tried our "Send" button on the home page?
