### ISSUE TITLE
I'm having trouble connecting to the wallet

### ISSUE THREAD

**Issue by Mikail23** [suiet/suiet#206]
Hello, I was using the suiet wallet to testnets on the sui platform before. Wispswap, suisswap etc. for 4-5 days. I can't get into the programs. I uninstalled and reinstalled Suiet wallet, still didn't work.

**Comment by bruceeewong** [comment]
Can you provide some error screenshots for us to detect the issues? And please attach with your browser information and suite version

**Comment by Mikail23** [comment]
Chrome browser Suiet wallet version v0.2.31
***@***.***
Windows için Posta<https://go.microsoft.com/fwlink/?LinkId=550986> ile gönderildi

Kimden: ***@***.***>
Gönderilme: 11 Haziran 2023 Pazar 00:19
Kime: ***@***.***>
Bilgi: ***@***.***>; ***@***.***>
Konu: Re: [suiet/suiet] I'm having trouble connecting to the wallet (Issue #206)


Can you provide some error screenshots for us to detect the issues? And please attach with your browser information and suite version
