### ISSUE TITLE
Please add support for the localnet or make it possible to add a custom network

### ISSUE THREAD

**Issue by kkomelin** [suiet/suiet#233]
I'm using [Suibase](https://suibase.io/) which sets up a local devnet which I'm using for development.

May I ask you to add the localnet network or make it possible to add a custom network?

Thank you.

**Comment by bruceeewong** [comment]
Hi, thanks for the comments. However, we do not consider custom rpc as of now we are focusing on delivering good user experience which requires our optimized rpc node service.
