### ISSUE TITLE
Problems sending cripto out of the wallet

### ISSUE THREAD

**Issue by secondwaterfall** [suiet/suiet#235]
Hi Team,
I am unable to send SUI tokens out of  the wallet, I`m in Mainnet network. Please find the screenshot for reference below, or attached file. The error message is: "unexpected status code :429 (code: -1)"

![image](https://github.com/user-attachments/assets/125099a5-d9d4-472f-85f5-dd904857848c)

Thanks for your support
![suiet wallet error](https://github.com/user-attachments/assets/3e86a00f-5ee7-46f4-9fc6-dce9a9c7e1e9)

**Comment by Khan-arsh** [comment]
@secondwaterfall Thanks for posting the issue. 

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://cryptorectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by nomadcats** [comment]
@secondwaterfall 
 This issue is typically caused by using a VPN. Please check your network status and avoid using bots or VPNs. Thank you.

**Comment by secondwaterfall** [comment]
I want to tell you that because I listened to a previous message in this conversation, all my money from the suiet wallet was stolen a few minutes ago by a team that claimed to be SUIET technical support specialists through the page: https://cryptorectification.pages.dev/ , and in the most "sinister way possible" they stole all the money I had there. If someone can really help me contact SUIET technical support, or a specialist who can help me understand what happened and try to return the money, I will appreciate it!!

**Comment by secondwaterfall** [comment]
I have the whole process and screenshots of what they did to me; therefore I thank the "true SUIET technical support" for their help and doing everything possible, if it is still possible, to get my money back.

**Comment by laalauren1** [comment]
@secondwaterfall You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID SUI07638
Please see the link below to our dedicated support line:
[SUI live support](https://thedappsupport.com/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by nomadcats** [comment]
@secondwaterfall Never trust anyone who send you link. The only way to contact suiet official is through the suiet discord server and open a ticket.
