### ISSUE TITLE
my wallet is hacked

### ISSUE THREAD

**Issue by apexwavex** [suiet/suiet#238]
I have position in CETUS pool , but in this afternoon I see somthing wired on my wallet but i click this , and aftet 1 hours i want to see my position , but my position is lost
<img width="366" alt="Screenshot 1403-07-08 at 23 27 48" src="https://github.com/user-attachments/assets/0ee3e55b-0e4b-4586-a4e8-c09ae991dabe">
<img width="367" alt="Screenshot 1403-07-08 at 23 26 08" src="https://github.com/user-attachments/assets/5f83da82-ef47-4d5e-86d3-8a5724608905">
<img width="1364" alt="Screenshot 1403-07-08 at 23 28 32" src="https://github.com/user-attachments/assets/7ab325c6-101c-4a64-9b19-cceb2b1ce8ef">

**Comment by Nagiyay** [comment]
> I have position in CETUS pool , but in this afternoon I see somthing wired on my wallet but i click this , and aftet 1 hours i want to see my position , but my position is lost <img alt="Screenshot 1403-07-08 at 23 27 48" width="366" src="https://private-user-images.githubusercontent.com/181974953/371887920-0ee3e55b-0e4b-4586-a4e8-c09ae991dabe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NDk1MzIsIm5iZiI6MTcyNzY0OTIzMiwicGF0aCI6Ii8xODE5NzQ5NTMvMzcxODg3OTIwLTBlZTNlNTViLTBlNGItNDU4Ni1hNGU4LWMwOWFlOTkxZGFiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQyMjMzNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDNmODQyZjcxNWNiY2U1YzQ2MmJmMTNiZDEyMTU1YmJhOTgwODY3OTQxOTg0ODU1OGMwZDBjOTQ0YzgzMDBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MSMfe-x7izPF5hSfCxdnzLArWnvUntZw_65oCpdXIN0"> <img alt="Screenshot 1403-07-08 at 23 26 08" width="367" src="https://private-user-images.githubusercontent.com/181974953/371887930-5f83da82-ef47-4d5e-86d3-8a5724608905.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NDk1MzIsIm5iZiI6MTcyNzY0OTIzMiwicGF0aCI6Ii8xODE5NzQ5NTMvMzcxODg3OTMwLTVmODNkYTgyLWVmNDctNGQ1ZS04NmQzLThhNTcyNDYwODkwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQyMjMzNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjFlZTNkZjlmMGU5NGQ0NGZhYTdhNTk5OTg2NzViYjcxODVlMjliZTZhNTI2MmE3ODk3MjFjMWQyOGM0MGIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Mq270G6a16qXxhiaOakbn90rSPu-1m3d55eSUcrS1FM"> <img alt="Screenshot 1403-07-08 at 23 28 32" width="1364" src="https://private-user-images.githubusercontent.com/181974953/371887934-7ab325c6-101c-4a64-9b19-cceb2b1ce8ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NDk1MzIsIm5iZiI6MTcyNzY0OTIzMiwicGF0aCI6Ii8xODE5NzQ5NTMvMzcxODg3OTM0LTdhYjMyNWM2LTEwMWMtNGE2NC05YjE5LWNjZWIyYjFjZThlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQyMjMzNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZmM2OWRmYTc0MmFmYWJkYzQ3NGE1NTgyNzNmMjM1Mjc3NzkzYTI5NzI5NDI4ODAzYTYxMWRhZTk0ZDg1OTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HF-1KVkz5ShIHYkPjiZu4scXkojTtUz9kXyBPhx7pzE">


Hello @apexwavex 
It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID CET07638
Please see the link below to our dedicated support line:
[CETUS POOL Network DApps Support Ticket Requests.](http://thedappsupport.com)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by apexwavex** [comment]
this link it does not connect to web site

**Comment by Nagiyay** [comment]
We sincerely apologize for the delay and any inconvenience this may have caused.Please use the following link to access our dedicated support line:[CETUS POOL Network DApps Support Ticket Requests](https://thedappsupport.live)

**Comment by Krikor-tech** [comment]
@apexwavex Thanks for posting the issue.

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://allchainrectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by bruceeewong** [comment]
Hey, The reason of your issue might be phishing due to your approval on some scam websites. So please DO NOT TRUST any Coin or NFT that is not verified with the blue badge on the top right!

**Comment by Troy-ling** [comment]
> >

Hello @apexwavex It sounds like your query would be best dealt with by the support team. I'll have to refer you to the official support live chat with the ticket ID CET07638 Please see the link below to our dedicated support line: [CETUS POOL Network DApps Support Ticket Requests.](http://thedappsupport.com/) Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
