### ISSUE TITLE
Unstake Error

### ISSUE THREAD

**Issue by bobo443** [suiet/suiet#239]
Set up suiet wallet in Chrome browser on PC. Clicked on stake button but didnt see which validator I staked with. Waited a day to unstake. Now  when I try to unstake, I get message "Send transaction failed: Error: Transaction execution failed due to issues with transaction inputs, please review the errors and try again: - Balance of gas object 750000 is lower than the needed amount: 10025452 (code: -32002)"
Help please. Im new to this.

**Comment by Julietnacy** [comment]
@bobo443 It sounds like you're encountering a gas fee issue with your transaction. I'll have to refer you to the official support live chat with the ticket ID SUI07638
Please see the link below to our dedicated support line:
[Suiet Network DApps Support Ticket Requests.](https://thedappsupport.com/)
 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent

**Comment by bruceeewong** [comment]
> Set up suiet wallet in Chrome browser on PC. Clicked on stake button but didnt see which validator I staked with. Waited a day to unstake. Now  when I try to unstake, I get message "Send transaction failed: Error: Transaction execution failed due to issues with transaction inputs, please review the errors and try again: - Balance of gas object 750000 is lower than the needed amount: 10025452 (code: -32002)"
> 
> Help please. Im new to this.

Hey, the error indicates that your balance was not sufficient to pay the gas fee of the unstaking operation. Could you check if it works after you fuel some more SUI to your account?

**Comment by Andrewleach1** [comment]
> Set up suiet wallet in Chrome browser on PC. Clicked on stake button but didnt see which validator I staked with. Waited a day to unstake. Now when I try to unstake, I get message "Send transaction failed: Error: Transaction execution failed due to issues with transaction inputs, please review the errors and try again: - Balance of gas object 750000 is lower than the needed amount: 10025452 (code: -32002)" Help please. Im new to this.


Hello @bobo443 
Thanks for posting the issue.

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://thedappsupport.live/)

Note: Click on the live chat icon at the bottom corner of the page to start a conversation with the ticket ID UNS107638

**Comment by bobo443** [comment]
Yes I added some more SUI and it unstaked. The problem is Im still only seeing a STAKE button and it stakes without selecting a validator. Thats what it did the first time. Scared if I click on it again it will do the same thing.
![suifile](https://github.com/user-attachments/assets/e2b84d1d-f2a1-4a64-9339-cc799a414bbf)

**Comment by LeoNore-ort** [comment]
@bobo443 Thanks for posting the issue.

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://chainrectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by bruceeewong** [comment]
@bobo443 Hey, I don't get what you mean because there is a staking option page after you click the Stake button where the validator selector is on the top.
![image](https://github.com/user-attachments/assets/ea288121-8635-4b72-9a42-db825e5dff9b)

Can you please check your wallet version if it is the latest? v0.3.2 for now (by choosing wallet section > settings > scroll to the bottom and you will see the version)
