### ISSUE TITLE
Error message is displayed When User clicks "Airdrop" button on Wallet

### ISSUE THREAD

**Issue by AndriiMelnychenko** [suiet/suiet#91]
*Environment*
devnet

*OS*
Windows 10

*Browser*
Google Chrome
Version 106.0.5249.119 (Official Build) (64-bit)

*Steps to reproduce*
1. Create wallet
2. Click on wallet
3. Click on "Airdrop" button
4. Verify error message

*Actual result*
"Unexpected token '<', ">!DOCTYPE"...is not valid JSON" error message is displayed

*Expected result*
SUI coin should be added to wallet

![bug with airdrop](https://user-images.githubusercontent.com/116204490/196774818-822f4ac2-0595-4086-b995-1632573b395d.jpg)

**Comment by bruceeewong** [comment]
Duplicated issue. Plz check this issue #94

**Comment by AndriiMelnychenko** [comment]
@bruceeewong My issue has #91 number. So, I would say that #94 is a duplicate issue :)
