### ISSUE TITLE
"Back" button doesn't work on New Wallet creation

### ISSUE THREAD

**Issue by AndriiMelnychenko** [suiet/suiet#92]
*Environment*
devnet

*OS*
Windows 10

*Browser*
Google Chrome 
Version 106.0.5249.119 (Official Build) (64-bit)

*Steps to reproduce*
1. Open All Wallets list
2. Click "New" button
3. Click on "<-" back button

*Actual result*
This option is disabled

*Expected result*
"<-" back button should back User to All Wallets list

![back button doesn't work](https://user-images.githubusercontent.com/116204490/196776539-05bc5c9a-bd1e-49b9-9600-7279e0feb405.jpg)

**Comment by bruceeewong** [comment]
Sorry for the misunderstanding. We thought user should click the "confirm" rather than the back button. We will remove the back button in this case. Thanks for the feedback
