### ISSUE TITLE
New Wallet will be created without clicking on "Confirm and Create" button

### ISSUE THREAD

**Issue by AndriiMelnychenko** [suiet/suiet#93]
*Environment*
devnet

*OS*
Windows 10

*Browser*
Google Chrome
Version 106.0.5249.119 (Official Build) (64-bit)

*Steps to reproduce*
1. Open SUI Wallet
2. Open All Wallets List
3. Click on "New" button
4. Click on any place (except the Wallet pop up) 
5. Wallet was closed
6. Open again SUI Wallet
7. Verify number of Wallets

*Actual result*
New Wallet was created without clicking on "Confirm and Create" button

*Expected result*
New Wallet should not be created without clicking on "Confirm and Create" button

![Wallets](https://user-images.githubusercontent.com/116204490/196778708-0dae77fd-b21e-434f-a1ac-cc00e13396fd.jpg)

**Comment by bruceeewong** [comment]
Well, at the time clicking "New" button, the new wallet has already been created (otherwise the mnemonic can't be displayed). So I would say it is not a good UX design rather than a bug. So I'm gonna close this issue and consider the UX logic here. 
Anyway, thanks for the feedback!
